apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jenkins
    project: palinta
  name: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
